return {
  name = "Kanagawa",
  background = "dark",
  colors = {
    bg = "#1f1f28",
    bg_dark = "#16161d",
    bg_highlight = "#2a2a37",
    fg = "#dcd7ba",
    blue = "#7e9cd8",
    cyan = "#6a9589",
    green = "#98bb6c",
    magenta = "#957fb8",
    purple = "#938aa9",
    red = "#c34043",
    orange = "#ffa066",
    yellow = "#e6c384",
    grey = "#54546d",
  },
  groups = {
    KeywhizNormal = { fg = "fg", bg = "bg" },
    KeywhizBorder = { fg = "grey" },
    KeywhizTitle = { fg = "blue", bold = true },
    KeywhizLeader = { fg = "purple", bold = true },
    KeywhizCtrl = { fg = "red" },
    KeywhizAlt = { fg = "green" },
    KeywhizShift = { fg = "orange" },
    KeywhizSpecial = { fg = "magenta" },
    KeywhizLSP = { fg = "cyan", italic = true },
    KeywhizFavorite = { fg = "yellow", bold = true },
    KeywhizConflict = { fg = "red", bold = true },
  },
}
