return {
  name = "Spacedust",
  background = "dark",
  colors = {
    bg = "#0a0b11",
    bg_dark = "#06070b",
    bg_highlight = "#1b1c27",
    fg = "#c4c6c9",
    blue = "#51afef",
    cyan = "#5cefff",
    green = "#7bc275",
    magenta = "#c678dd",
    purple = "#a9a1e1",
    red = "#ff6c6b",
    orange = "#da8548",
    yellow = "#ecbe7b",
    grey = "#3f444a",
  },
  groups = {
    KeywhizNormal = { fg = "fg", bg = "bg" },
    KeywhizBorder = { fg = "grey" },
    KeywhizTitle = { fg = "blue", bold = true },
    KeywhizLeader = { fg = "purple", bold = true },
    KeywhizCtrl = { fg = "magenta" },
    KeywhizAlt = { fg = "cyan" },
    KeywhizShift = { fg = "orange" },
    KeywhizSpecial = { fg = "yellow" },
    KeywhizLSP = { fg = "blue", italic = true },
    KeywhizFavorite = { fg = "yellow", bold = true },
    KeywhizConflict = { fg = "red", bold = true },
  },
}
