return {
  name = "Gruvbox",
  background = "dark",
  colors = {
    bg = "#282828",
    bg_dark = "#1d2021",
    bg_highlight = "#3c3836",
    fg = "#ebdbb2",
    blue = "#83a598",
    cyan = "#8ec07c",
    green = "#b8bb26",
    magenta = "#d3869b",
    purple = "#b16286",
    red = "#fb4934",
    orange = "#fe8019",
    yellow = "#fabd2f",
    grey = "#928374",
  },
  groups = {
    KeywhizNormal = { fg = "fg", bg = "bg" },
    KeywhizBorder = { fg = "grey" },
    KeywhizTitle = { fg = "blue", bold = true },
    KeywhizLeader = { fg = "purple", bold = true },
    KeywhizCtrl = { fg = "red" },
    KeywhizAlt = { fg = "green" },
    KeywhizShift = { fg = "orange" },
    KeywhizSpecial = { fg = "magenta" },
    KeywhizLSP = { fg = "cyan", italic = true },
    KeywhizFavorite = { fg = "yellow", bold = true },
    KeywhizConflict = { fg = "red", bold = true },
  },
}
