return {
  name = "Nord",
  background = "dark",
  colors = {
    bg = "#2e3440",
    bg_dark = "#272c36",
    bg_highlight = "#3b4252",
    fg = "#d8dee9",
    blue = "#81a1c1",
    cyan = "#88c0d0",
    green = "#a3be8c",
    magenta = "#b48ead",
    purple = "#5e81ac",
    red = "#bf616a",
    orange = "#d08770",
    yellow = "#ebcb8b",
    grey = "#4c566a",
  },
  groups = {
    KeywhizNormal = { fg = "fg", bg = "bg" },
    KeywhizBorder = { fg = "grey" },
    KeywhizTitle = { fg = "blue", bold = true },
    KeywhizLeader = { fg = "cyan", bold = true },
    KeywhizCtrl = { fg = "magenta" },
    KeywhizAlt = { fg = "green" },
    KeywhizShift = { fg = "orange" },
    KeywhizSpecial = { fg = "purple" },
    KeywhizLSP = { fg = "blue", italic = true },
    KeywhizFavorite = { fg = "yellow", bold = true },
    KeywhizConflict = { fg = "red", bold = true },
  },
}
