return {
  name = "Tokyo Night",
  background = "dark",
  colors = {
    bg = "#1a1b26",
    bg_dark = "#16161e",
    bg_highlight = "#292e42",
    fg = "#c0caf5",
    blue = "#7aa2f7",
    cyan = "#7dcfff",
    green = "#9ece6a",
    magenta = "#bb9af7",
    purple = "#9d7cd8",
    red = "#f7768e",
    orange = "#ff9e64",
    yellow = "#e0af68",
    grey = "#565f89",
  },
  groups = {
    KeywhizNormal = { fg = "fg", bg = "bg" },
    KeywhizBorder = { fg = "grey" },
    KeywhizTitle = { fg = "blue", bold = true },
    KeywhizLeader = { fg = "purple", bold = true },
    KeywhizCtrl = { fg = "red" },
    KeywhizAlt = { fg = "green" },
    KeywhizShift = { fg = "orange" },
    KeywhizSpecial = { fg = "magenta" },
    KeywhizLSP = { fg = "cyan", italic = true },
    KeywhizFavorite = { fg = "yellow", bold = true },
    KeywhizConflict = { fg = "red", bold = true },
  },
}
